### ISSUE TITLE
comma before notes

### ISSUE THREAD

**Issue by zmoon** [claytoncook12/VGSDBWebsite#2]
Example:
![image](https://user-images.githubusercontent.com/15079414/132565655-0aadfa5f-177b-42d6-ba04-edd09a87daaa.png)

Culprit:
https://github.com/claytoncook12/VGSDBWebsite/blob/86eb61c8682f54600b2f6b45630b0f77240c2d6c/DjangoApp/session/templates/session/session_detail.html#L80-L82

Very cool site!

**Comment by claytoncook12** [comment]
Should be resolved. #3  

Thanks for the info.
